#By AlexDeveloperUwU
name: AoiiMipMC GH-Pages Publisher

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.11.1]
        
    steps:
    - uses: actions/checkout@v2
    - name: Build and publish
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build
    - run: cd ./src/.vuepress/
    - uses: JamesIves/github-pages-deploy-action@4.1.5
      with:
          branch: gh-pages
          folder: ./src/.vuepress/dist
